server:
  port: 5001

mybatis-plus:
  type-aliases-package: com.nacos.pojo
  mapper-locations: classpath:com/nacos/mapper/xml/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

spring:
  application:
    name: nacos-seata-bill
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848
    sentinel:
      dashboard: 127.0.0.1:8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bill?serverTimezone=GMT
    username: root
    password: root

seata:
  enabled: true     # 1.0新特性，需要依赖seata-spring-boot-starter,默认为true
  tx-service-group: bdqn_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: http://127.0.0.1:8848
  client:
    support:
      spring:
        datasource-autoproxy: false
  service:
    disable-global-transaction: false   #bug

management:
  endpoints:
    web:
      exposure:
        include: "*"